p=input('digite algo')
print('o tipo primitivo desse valor é',type(p))
#n=('é numerico?')
l=('é letra?')
ln=('é letra e numero?')
lm=('tem apenas letras maiúscolas?')
lmi=('tem apenas letras minúscolas?')
print(('{}'.format('é numerico?')),(p.isnumeric()))
print(('{}'.format(l)),(p.isalpha()))
print(('{}'.format(ln)),(p.isalnum()))
print(('{}'.format(lm)),(p.isupper()))
print(('{}'.format(lmi)),(p.islower()))
print('só tem espaço?',p.isspace())
print('está capitalizada?(maiusculas e minusculas)',p.istitle())
#print('está capitalizada?(maiusculas e minusculas) e numeros?',p.isupper()and p.isalnum()and p.islower())
